### ISSUE TITLE
Вопросы по заданию

### ISSUE THREAD

**Issue by GurinaElena** [GurinaElena/transferMoney#1]
Добрый день!

Понимаю что тест "сырой", но т.к. есть вопросы скинула то что есть.

1. Поиск конкретного элемента

У меня в тесте есть строчка 44 $("[data-test-id=action-deposit]").click();, но элементов с таким data-test-id два, а я хочу нажать именно на первую кнопку, написала
   SelenideElement actionForFirstCard = $(".list__item").find("[data-test-id=92df3f1c-a033-48e6-8390-206f6b1f56c0]").find("[data-test-id=action-deposit]");
        actionForFirstCard.click();
На этой строчке тест стал падать, хотя вроде все логично... Как еще модно добраться до конкретной кнопки?

2. Пыталась реализовать проверку баланса до операции, написала 
        val balance = new LoginPage.ExtraBalance();
        val balanceOne = balance.getFirstCardBalance();
По-другому что-то не получается сделать наследование метода, но на этом тест стал падать, при чем в дебаге падает строчка
val text = cards.first().text(); из LoginPage и соответственно    
val balanceOne = balance.getFirstCardBalance();
Как прописать по-другому пока идей нет( чтение кучи форумов только каши в голове добавили(

Заранее большое спасибо!

**Comment by ArRomanov** [comment]
Добрый день!
1. `SelenideElement actionForFirstCard = $(".list__item").find("[data-test-id='92df3f1c-a033-48e6-8390-206f6b1f56c0']").find("[data-test-id='action-deposit']");` Здесь я добавил только кавычки, а в ide у вас некорректный селектор - `.find("[92df3f1c-a033-48e6-8390-206f6b1f56c0]")`
2. 
![image](https://user-images.githubusercontent.com/23121947/88511045-d7531800-cfec-11ea-80a3-7d79c3a105b5.png)
Элементы, текст одно из которых вы пытаетесь взять, не содержат текста. Вам надо искать непосредственно карты - 
![image](https://user-images.githubusercontent.com/23121947/88511201-1e410d80-cfed-11ea-825a-a217ad95e6d2.png)
